config/routes.rb
Rails.application.routes.draw do
  resources :books
  devise_for :users
  root 'pages#home'

  get 'dashboard' => "pages#dashboard"

  post '/buy/:slug', to: 'transactions#create', as: :buy 
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :read, :all? 
    can :manage, Book do |book|
        book.try(:user) == user
    end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: :slugged 

	has_many :sales
	belongs_to :user
	has_attached_file :image 
	has_attached_file :resource

    validates_numericality_of :price, 
		greather_then: 49, message: "Must be at least 50 cents"
		
	validates_attachment_content_type :image, 
		content_type:  /^image\/(png|gif|jpeg)/,
		message: "Only images allowed"
	validates_attachment_content_type :resource, 
		content_type: ['application/pdf'],
		message: "Only pdfs allowed"	

	validates :image, attachment_presence: true 
	validates :resource, attachment_presence: true 
end

app/models/sale.rb
class Sale < ActiveRecord::Base

	before_create :populate_guid
	belongs_to :book
	
	include AASM

	aasm column: 'state' do 
		state :pending, initial: true 
		state :processing 
		state :finished 
		state :errored 

		event :process, after: :charge_card do 
			transitions from: :pending, to: :processing
		end

		event :finish do 
			transitions from: :processing, to: :finished 
		end

		event :fail do  
			transitions from: :processing, to: :errored 
		end
	end

	def charge_card 
		begin
				save! 
			charge = Stripe::Charge.create(
				amount: self.amount, 
				currency: "usd",
				card: self.stripe_token,
				description: "Book Sale"
				)
			self.update(stripe_id: charge.id)	 
			self.finish! 
		rescue Stripe::StripeError => e
			self.update_attributes(error: e.message)
			self.fail!
		end
	end

	private 

		def populate_guid
			self.guid = SecureRandom.uuid()
		end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to root_path, notice: "You are not authorized to access this area"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  # GET /books
  # GET /books.json
  def index
    @books = Book.where(availability: true)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    authorize! :manage, @book
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    authorize! :manage, @book
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    authorize! :manage, @book
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :description, :price, :availability, :author, :image, :resource)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only: [:dashboard]
  def home
  	if current_user
  		redirect_to books_path
  	end
  	@books = Book.last(4)
  end

  def dashboard
  	@books = current_user.books
    @purchased = Sale.where(buyer_email: current_user.email)
    @sales = Sale.where(buyer_email: current_user.email)
  end

end

app/controllers/transactions_controller.rb
class TransactionsController< ApplicationController

	def create
		book = Book.find_by!(slug: params[:slug])
		sale = book.sales.create(
			amount: book.price, 
			buyer_email: current_user.email, 
			seller_email: book.user.email, 
			stripe_token: params[:stripeToken])
		sale.process!
		
		if sales.finished?
		redirect_to pickup_url(guid: @sale.guid)
		else
		redirect_to book_path(book), notice: @error
		end
	end

	def pickup
		@sale = Sale.find_by!(guid: params[:guid])
		@book = @sale.book
	end
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_book.html.erb
<div class="col-md-3">
    <div class="thumbnail">
    <%= link_to book_path(book) do %>
       <%= image_tag book.image.url(:original), class: "img-responsive" %>
      <% end %>
      <div class="caption">
        <p><strong><%= link_to book.name, book_path(book) %></strong></p>
        <p>$<%= book.price.to_f / 100 %></p>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for(@book, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>

    <%= f.input :name, required: true, label: false, placeholder: "Name", input_html: { class: "form-control"} %>
    <%= f.input :author, required: true, label: false, placeholder: "Author", input_html: { class: "form-control"} %>
    <%= f.input :description, required: true, label: false, placeholder: "description", input_html: { class: "form-control"}, rows: 5 %>
    <%= f.input :price, required: true, label: false, placeholder: "price", input_html: { class: "form-control"} %>
    
    <%= f.input :image %>
    <%= f.input :resource %>
    
    <div class="checkbox text-center">
      <p>Availability</p>
      <%= f.input :availability, required: false, label: false %>
    </div>   


    <%= f.button :submit, class: "btn btn-primary btn-block" %>
<% end %>

app/views/books/edit.html.erb
<h1 class="text-center">Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="row">

  <%= render @books %>

</div>

app/views/books/new.html.erb
<h1 class="text-center">New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="container">
	<div class="row">

		<div class="col-md-6">
			<%= image_tag @book.image.url(:original), class: "img-responsive" %>
		</div>

		<div class="col-md-6">
			<h3><%= @book.name %> by <%= @book.author %></h3>
			<p class="justify"><%= @book.description %></p>
			<h4 class="text-right">$<%= @book.price.to_f / 100 %></h4>
		
			<% if current_user %>

			<%= form_tag buy_path(slug: @book.slug) do  %>
			  <script
			    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
			    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
			    data-amount="	<%= @book.price %>"
			    data-name="eStuk"
			    data-description=" <%= @book.name %>"
			    data-email="<%= current_user.email %>"
			    data-locale="auto">
			  </script>
			<% end %>

		<% else %>
			<p>Please login first to Buy</p>
		<% end %>
		
		</div>

	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "Bookshelf", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Books", books_path %></li>
        <% if current_user %>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Dashboard", dashboard_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li>
        <%= link_to "Login", new_user_session_path %>
      </li>
      <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookshelf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<div class= "container">
	<% flash.each do |type, message| %>
	<div class="alert alert-info fade-in">
	<button class="close" data-dismiss="alert">x</button>
	<%= message %>
	</div>
	<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/pages/_books.html.erb
<table class="table table-condensed"> 
	<thead> 
		<tr> 
			<th>Id</th> 
			<th>Name</th> 
			<th>Available</th> 
			<th></th> 
		</tr> 
	</thead> 
	<tbody> 
		<% @books.each do |book| %> 
		<tr> 
			<td><%= book.id %></td>
			<td><%= link_to book.name, book_path(book) %></td> 
			<td><%= book.availability %></td> 
			<td><%= link_to "edit", edit_book_path(book) %></td> 
		</tr> 
		<% end %>
 </tbody> 
</table>

app/views/pages/_purchased.html.erb
<table class="table table-condensed"> 
	<thead> 
		<tr> 
			<th>Name</th> 
			<th>Date</th> 
		</tr> 
	</thead> 
	<tbody> 
		<% @purchased.each do |sale| %> 
		<tr> 
			<td><%= link_to sale.book.name, pickup_path(sale.guid) %></td> 
			<td><%= time_ago_in_words(sale.created_at) %> ago</td> 
		</tr> 
		<% end %>
 </tbody> 
</table>

app/views/pages/_sales.html.erb
<table class="table table-condensed"> 
	<thead> 
		<tr> 
			<th>Name</th> 
			<th>Date</th> 
			<th>Buyer</th> 
		</tr> 
	</thead> 
	<tbody> 
		<% @sales.each do |sale| %> 
		<tr> 
			<td><%= link_to sale.book.name, pickup_path(sale.guid) %></td> 
			<td><%= time_ago_in_words(sale.created_at) %> ago</td> 
			<td><%= sale.buyer_email %></td> 
		</tr> 
		<% end %>
 </tbody> 
</table>

app/views/pages/dashboard.html.erb
<div class="row">
	<h1 class="text-center">Dashboard</h1>
	
	<div class="col-md-4">
		<h3 class="text-center">
			Books <%= link_to "New Book", new_book_path, class: "btn btn-primary btn-sm" %>
		</h3>  
		
		<%= render 'books' %>

	</div>

	<div class="col-md-4">
		<h3 class="text-center">Purchased</h3>
		<%= render 'purchased' %>  
	</div>

	<div class="col-md-4">
		<h3 class="text-center">Sales</h3> 
		<%= render 'sales' %> 
	</div>

</div>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>Welcome to our store</h1>
	<p>This is online Digital Books Store</p>
	<%= link_to "Books", books_path, class: "btn btn-primary" %>
	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
</div>

<div class="row">
	<%= render @books %> 
</div>

app/views/transactions/pickup.html.erb
<div class="row text-center">
	<br>
	<h1>Congratulations! </h1> 
	<br>
	<h3>Thanks for buying <i>" <%= @sale.book.slug %> "</i> <br>
	Here is the <%= link_to "download", @book.resource.url  %> link. </h3>
</div>